baseURL: "https://vhimani.github.io" 
title: Himani Verma
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: about/
          weight: 2 
        - name: Research
          url: research/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4

params:
    description: "This website hosts Himani Verma's research papers, curriculum vitae, and contact information."
    author: Himani Verma
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","research","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Himani Verma
          subtitle: "I am a Senior Research Analyst at The Brattle Group, an economic consulting firm, in San Francisco. I graduated from The University of Texas at Austin with a BA in Economics Honors and BS in Mathematics, with additional minors in Computer Science and Applied Statistical Modeling."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Research
              url: research/
            - name: Blog
              url: blog/

    socialIcons:
        - name: CV
          url: cv.pdf
          title: "CV"
        - name: Email
          url: mailto:himani.verma@uci.edu
          title: "Email"
        - name: GitHub
          url: https://github.com/vhimani
          title: "GitHub"
        - name: LinkedIn
          url: https://www.linkedin.com/in/vermahimani/
          title: "LinkedIn"

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Himani Verma"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
